name: Build

on:
  push:
    branches: [ main, master ]

env:
  WORKING_DIRECTORY: application

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: pnpm build
        working-directory: "application"
